# Change these first
owner: rafaeldebridge # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: deBridge APP
    url: https://app.debridge.finance/

status-website:  
  baseUrl: /status  
  name: deBridge Status Page
  logoUrl: https://debridge.finance/assets/img/logo/debridge-dark.svg
  shouldShowIncidentIssues: true
  navbar:
    - title: deBridge
      href: https://debridge.finance
    - title: deBridge App
      href: https://app.debridge.finance/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
